import { invoke } from "@tauri-apps/api/core";
import type { DeepPartial, HwInfo, ModelStatus, Provider, SegmentRow, SessionSummary, Settings, TestTranslationResult } from "./types";

export const api = {
  getSettings: () => invoke<Settings>("get_settings"),
  patchSettings: (patch: DeepPartial<Settings>) => invoke<void>("patch_settings", { patch }),
  getPlatform: () => invoke<string>("get_platform"),
  checkAudioPermission: () => invoke<"granted" | "denied" | "unknown">("check_audio_permission"),
  openPrivacySettings: () => invoke<void>("open_privacy_settings"),
  finishOnboarding: () => invoke<void>("finish_onboarding"),
  overlaySetAdjustMode: (enabled: boolean) => invoke<void>("overlay_set_adjust_mode", { enabled }),
  overlayCommitPosition: () => invoke<void>("overlay_commit_position"),
  getModels: () => invoke<ModelStatus[]>("get_models"),
  downloadModel: (id: string) => invoke<void>("download_model", { id }),
  cancelDownload: (id: string) => invoke<void>("cancel_download", { id }),
  deleteModel: (id: string) => invoke<void>("delete_model", { id }),
  startCapture: () => invoke<void>("start_capture"),
  stopCapture: () => invoke<void>("stop_capture"),
  captureState: () => invoke<boolean>("capture_state"),
  getHwInfo: () => invoke<HwInfo>("get_hw_info"),
  historySessions: (limit: number) => invoke<SessionSummary[]>("history_sessions", { limit }),
  historySegments: (id: number) => invoke<SegmentRow[]>("history_segments", { sessionId: id }),
  historySearch: (q: string) => invoke<SegmentRow[]>("history_search", { q }),
  historyDelete: (id: number) => invoke<void>("history_delete", { sessionId: id }),
  historyExport: (id: number, format: "txt" | "srt") => invoke<string>("history_export", { sessionId: id, format }),
  setApiKey: (provider: Provider, key: string) => invoke<void>("set_api_key", { provider, key }),
  hasApiKey: (provider: Provider) => invoke<boolean>("has_api_key", { provider }),
  deleteApiKey: (provider: Provider) => invoke<void>("delete_api_key", { provider }),
  testTranslation: () => invoke<TestTranslationResult>("test_translation"),
};
